#!/bin/bash
# GitHub Secrets Setup Guide

echo "🔐 GitHub Secrets Setup for HereSphere Stash Bridge"
echo "=================================================="
echo ""
echo "To enable CI/CD workflows, you need to set up the following secrets in your GitHub repository:"
echo ""
echo "1. Go to your GitHub repository"
echo "2. Navigate to Settings → Secrets and variables → Actions"
echo "3. Click 'New repository secret' and add the following:"
echo ""

echo "📦 Docker Hub Secrets:"
echo "----------------------"
echo "DOCKERHUB_USERNAME     - Your Docker Hub username"
echo "DOCKERHUB_TOKEN        - Your Docker Hub access token (not password!)"
echo ""
echo "To create a Docker Hub access token:"
echo "1. Go to https://hub.docker.com/settings/security"
echo "2. Click 'New Access Token'"
echo "3. Give it a name like 'github-actions'"
echo "4. Copy the token and use it as DOCKERHUB_TOKEN"
echo ""

echo "🔧 Optional Secrets:"
echo "-------------------"
echo "CODECOV_TOKEN          - For code coverage reports (optional)"
echo ""

echo "📋 Environment Variables (set in .env for local development):"
echo "------------------------------------------------------------"
echo "SECRET_KEY             - Flask secret key"
echo "HERESPHERE_HOST        - HereSphere server host"
echo "HERESPHERE_PORT        - HereSphere server port"
echo "STASH_HOST             - Stash server host"
echo "STASH_PORT             - Stash server port"
echo "STASH_API_KEY          - Stash API key"
echo "BRIDGE_HOST            - Bridge server host"
echo "BRIDGE_PORT            - Bridge server port"
echo ""

echo "🚀 After setting up secrets:"
echo "----------------------------"
echo "- Push to main branch to trigger CI/CD"
echo "- Create a tag like 'v1.0.0' to trigger a release build"
echo "- Pull requests will run tests automatically"
echo ""

echo "💡 Tips:"
echo "--------"
echo "- Use 'v' prefix for version tags (e.g., v1.0.0, v1.1.0)"
echo "- The main branch builds are tagged as 'latest'"
echo "- Multi-architecture builds (AMD64 + ARM64) are enabled"
echo "- Security scans run on every push"
echo ""